context:
  version: "16.1.5"

package:
  name: lint-staged
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/lint-staged/-/lint-staged-${{ version }}.tgz
  sha256: bd0bc9895934f729e232f0f6bcde98a95e12f17f5d2908e5cbf150a0d0b0b78b

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - lint-staged --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Run linters on git staged files
  homepage: https://github.com/lint-staged/lint-staged
  repository: https://github.com/lint-staged/lint-staged

extra:
  recipe-maintainers:
    - danielnachun
