context:
  version: "17.5.1"

package:
  name: lint-staged
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/lint-staged/-/lint-staged-${{ version }}.tgz
  sha256: bb07660621709ba36ee3ba0ba60c883cd56eb26a18a3eabc8b0856734951fed1

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - lint-staged --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Run linters on git staged files
  homepage: https://github.com/lint-staged/lint-staged
  repository: https://github.com/lint-staged/lint-staged

extra:
  recipe-maintainers:
    - danielnachun
