context:
  version: "17.5.0"

package:
  name: lint-staged
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/lint-staged/-/lint-staged-${{ version }}.tgz
  sha256: ebd1e273c7e79aa4f5577b0556b4878ac4d3b7aca5e639bc2ceb764a0e5dcc88

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - lint-staged --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Run linters on git staged files
  homepage: https://github.com/lint-staged/lint-staged
  repository: https://github.com/lint-staged/lint-staged

extra:
  recipe-maintainers:
    - danielnachun
