context:
  version: "17.0.4"

package:
  name: lint-staged
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/lint-staged/-/lint-staged-${{ version }}.tgz
  sha256: 3dc277cbb1476806350f9110fcfc6c1a8ce0d375aa733604853dcb9f50d6817c

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - lint-staged --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Run linters on git staged files
  homepage: https://github.com/lint-staged/lint-staged
  repository: https://github.com/lint-staged/lint-staged

extra:
  recipe-maintainers:
    - danielnachun
